### PR TITLE
deps: update parquet and arrow to 53.0.0

### PR DESCRIPTION
**Pull request by mihirn**

### CODE REVIEW

**Review by swlynch99 — COMMENTED** [review]
Does `metriken-exposition` expose either of these publically? If so this should be a major version bump, if not then this is fine as-is and LGTM.

**Comment by mihirn** [comment]
Do you mean re-exposed via `pub use`? If so, no, though happy to do a major bump just to be safer since the versioning with polars is not always very good.

**Comment by swlynch99** [comment]
It's not so much `pub use` as whether it is exposed as part of the public API, even if not re-exported.

Instead of just bumping the major version you can use `cargo semver-checks` to verify that it's not a breaking change :)

See https://github.com/obi1kenobi/cargo-semver-checks

**Comment by mihirn** [comment]
semver-checks seems happy enough with it at 0.9.2, but I'm still tempted to keep this as a major version, because having multiple versions of arrow/parquet/polars results in badness, and perhaps requiring things to opt into upgrades is nice.

Not a terribly strong opinion though...

**Comment by swlynch99** [comment]
If it is not part of the public API then that's not an issue, you just end up with multiple versions being compiled in. But tbh it really doesn't matter that much, feel free to go for the major version bump if you think it is appropriate.

**Pull request merged**
